name 'install_components'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install_components'
long_description 'Installs/Configures install_components'
version '0.3.2'
